seo: 
  site_name: My Conscious Community
  title: Default SEO Title
  description: Connect with Like-Minded Souls, Your Guide to Upcoming Workshops, Retreats, and Gatherings
  keywords: 
  social_image: 
  author: Brittany Woodard
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#302C2B'
  medium-text_color: '#C4B4C0'
  light-text_color: 'white'
  featured-text_color: '#F5B368'
  dark_color: 'rgb(60,60,65)'
  medium_color: '#F4D5BD'
  light_color: '#F5F2F5'
  v-light_color: '#FBF9FA'
  featured_color: '#6495ed'
  accent_color: '#d1c0ce'