seo: 
  site_name: My Conscious Community
  title: Default SEO Title
  description: Connect with Like-Minded Souls, Your Guide to Upcoming Workshops, Retreats, and Gatherings
  keywords: 
  social_image: 
  author: Brittany Woodard
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#302C2B'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#f7f5f3'
  featured-text_color: '#F5B368'
  dark_color: 'rgb(60,60,65)'
  medium_color: '#ede8e4'
  light_color: '#F5F2F5'
  v-light_color: '#f9f9f9'
  featured_color: '#6495ed'
  accent_color: '#DAC8D6'